### ISSUE TITLE
Help is not displayed if an OTR plugin is installed

### ISSUE THREAD

**Issue by alarig** [Ethylix/child#3]
Hi,

If you have an OTR plugin, '\x09  \x09\x09\x09\x09 \x09 \x09 \x09    \x09\x09  \x09 \x09' is send at the end of the message in queries to say to the other side “Hey, let’s encrypt of OTR!”.
But, if I send "help" to the bot, I don’t have the help but "No help available for \x09  \x09\x09\x09\x09 \x09 \x09 \x09    \x09\x09  \x09 \x09"

**Comment by target0** [comment]
This should be fix sinced https://github.com/Ethylix/child/commit/b7b80414b7dd9c6dd766fb5b47c8d2f5c4aaa349 (strip tab characters).
Thanks for reporting the issue !
